server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

logging:
  file: logs/robot.log
  file.max-size: 100MB
  file.max-history: 10
  level:
    root: info
    com.cy.robot: debug

spring:
  application:
    name: robot
  resources:
    add-mappings: true
    static-locations: classpath:/static/,classpath:/public/
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://39.108.143.76/example
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root

robot:
  name: 小歪
  # 调试模式
  debug: true
  embedding:
    file: support/embedding/word2vec.txt
  date-model : support/date/TimeExp.m
  processor:
    ignore-case: true
    trim-whitespace: true
    transfo-simplified: true
    transfo-half-width: true
  identifier:
    # 正则匹配开关
    regular-matching: true
    # 相似度匹配开关
    similar-matching: true
    # 相似度阈值
    similar-threshold: 0.75f
    # 问题配置文件列表
    files:
      - support/questions/weather.txt


